---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 10
        timeout: 600

    - name: install pip3
      apt: name=python3-pip state=present

  environment:
    - ENVIRONMENT='production'
    - TYPEORM_CONNECTION='${TYPEORM_CONNECTION}'
    - TYPEORM_ENTITIES='${TYPEORM_ENTITIES}'
    - TYPEORM_HOST='${TYPEORM_HOST}'
    - TYPEORM_PORT='${TYPEORM_PORT}'
    - TYPEORM_USERNAME='${TYPEORM_USERNAME}'
    - TYPEORM_PASSWORD='{TYPEORM_PASSWORD}'
    - TYPEORM_DATABASE='${TYPEORM_DATABASE}'

  roles:
    - configure-server