---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

# - name: Enabling users on port 80
#   become: true
#   shell: |
#     apt-get install libcap2-bin
#     setcap cap_net_bind_service=+ep /usr/local/bin/node

- name: Installing PM2
  become: true
  shell: |
    npm install pm2 -g

# - name: copy environment variable script
#   become: true
#   copy:
#     src: dbcontext.sh
#     dest: /etc/profile.d/dbcontext.sh

# - name: modify environment variable
#   become: true
#   blockinfile:
#     path: /etc/profile.d/dbcontext.sh
#     block: |
#       export ENVIRONMENT='production'
#       export TYPEORM_CONNECTION="{{ conn }}"
#       export TYPEORM_ENTITIES='{{ entities }}'
#       export TYPEORM_HOST='{{ dbhost }}'
#       export TYPEORM_PORT='{{ dbport }}'
#       export TYPEORM_USERNAME='{{ dbuser }}'
#       export TYPEORM_PASSWORD='{{ dbpwd }}'
#       export TYPEORM_DATABASE='{{ database }}'

# - name: Creates directory
#   file:
#     path: ~/web
#     state: directory

# - name: Copy app test page
#   template:
#     src: "files/app.js"
#     dest: "~/web/app.js"

# - name: Executing node
#   shell: |
#     pm2 start ~/web/app.js -f

