---
# - name: Creating user nodejsuser with permission of sudo
#   become: true
#   shell: |
#     useradd -s /bin/bash -m -d /home/nodejsuser -c "nodejs user" nodejsuser
#   #Give the safe user permission to use root level commands:
#     usermod -aG sudo nodejsuser

- name: setting python link and Install git
  become: true
  shell: |
      sudo ln -s /usr/bin/python3.8 /usr/bin/python
      apt-get install -y make
      apt-get install -y gcc
      apt-get -y install git

- name: Install nodejs and configure it correctly
  become: true
  shell: |
    sudo apt-get -y install build-essential
    sudo apt-get -y install curl openssl libssl-dev
    git clone https://github.com/joyent/node.git
    cd node
    git checkout v0.10.24
    ./configure
    make
    sudo make install
    node -v

- name: Enabling users on port 80
  become: true
  shell: |
    sudo apt-get install libcap2-bin
    sudo setcap cap_net_bind_service=+ep /usr/local/bin/node

- name: Installing PM2
  shell: |
    sudo npm install pm2 -g

- name: copy environment variable script
  become: true
  copy:
    src: context.sh
    dest: /etc/profile.d/dbcontext.sh

- name: modify environment variable
  become: true
  blockinfile:
    path: /etc/profile.d/dbcontext.sh
    block: |
      export ENVIRONMENT='production'
      export TYPEORM_CONNECTION="{{ conn }}"
      export TYPEORM_ENTITIES="{{ entities }}"
      export TYPEORM_HOST='{{ dbhost }}'
      export TYPEORM_PORT='{{ dbport }}'
      export TYPEORM_USERNAME='{{ dbuser }}'
      export TYPEORM_PASSWORD='{{ dbpwd }}'
      export TYPEORM_DATABASE='{{ database }}'

- name: copying test app.js
  copy:
    src: app.js
    dest: /tmp/app.js

- name: starting app.js
  shell: |
    pm2 start app.js

