---
# Compress backend
# copy backend
# uncompress backend....
- name: Copy backend builded files
  become: true
  copy:
    src: /home/circleci/project/backend/dist
    dest: "/home/ubuntu"

- name: Starting the backend
  become: true
  shell: |
    pwd
    ls -lart
    cd /home/ubuntu/dist
    pm2 start npm -- run start