---
- name: Copy backend builded files
  become: true
  copy:
    src: /home/circleci/project/backend/dist
    dest: "~/web"

- name: Starting the backend
  become: true
  shell: |
    pwd
    ls -lart
    cd ~/web/dist
    npm run start:prod